name: Ziggeo Publish SDK
on:
  push:
    branches: [ 'feature_publish_sdk' ]

jobs:
  drive_android:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [ 23 ]
        target: [ default ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@master

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Publish npm
        run: |
          npm publish
